version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    command: yarn start
  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app
    command: yarn start:dev
